### ISSUE TITLE
How to use in an existing nuxt project?

### ISSUE THREAD

**Issue by CuberHuber** [jo0707/QRGen#2]

**Comment by jo0707** [comment]
Hi, this project is designed as one independent web. If you only want to use one of its QR features, such as its scanner or generator, I recommend you to use its library directly such as [lean-qr](https://www.npmjs.com/package/lean-qr) or [qr-scanner](https://www.npmjs.com/package/qr-scanner).

However, if you really want to use all the content in this project in your project, here's how:

- Clone this project to your local machine (optional)
    ```bash
    git clone https://github.com/jo0707/QRGen
    ```
    _This step can help you move project content faster_
    
- install required dependencies for this project
     ```bash
    npm i lean-qr qr-scanner
    ```
    
- Copy all files (index.vue and scan.vue) from this project `/pages` to your project `/pages`, You can change the file name as needed
- Copy all files from this project `/components` to your project `/components`
- Finally, you can reuse the components or change the page design. (note: this project uses TailwindCSS/WindiCSS)
